// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMho-79pQz9slcFSebhl-lr_6-JR8v0eY',
    appId: '1:851141014710:web:14561722d2678665caa217',
    messagingSenderId: '851141014710',
    projectId: 'mynotes-dawid',
    authDomain: 'mynotes-dawid.firebaseapp.com',
    storageBucket: 'mynotes-dawid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBguQIe4m6bSt7RUzLjEU8FPEd1HmR2K6U',
    appId: '1:851141014710:android:af4028fd3d5d4d44caa217',
    messagingSenderId: '851141014710',
    projectId: 'mynotes-dawid',
    storageBucket: 'mynotes-dawid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtMH_tC_2c1mC_rdjJEq7coL4nGwfy5Jw',
    appId: '1:851141014710:ios:26b4af8ddebaf171caa217',
    messagingSenderId: '851141014710',
    projectId: 'mynotes-dawid',
    storageBucket: 'mynotes-dawid.appspot.com',
    iosClientId: '851141014710-qco7dbsn3oqtcvhgllj0862i461a2na1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtMH_tC_2c1mC_rdjJEq7coL4nGwfy5Jw',
    appId: '1:851141014710:ios:26b4af8ddebaf171caa217',
    messagingSenderId: '851141014710',
    projectId: 'mynotes-dawid',
    storageBucket: 'mynotes-dawid.appspot.com',
    iosClientId: '851141014710-qco7dbsn3oqtcvhgllj0862i461a2na1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
